services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: car_task_app
    environment:
      - DOCKER_PGHOST=db
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
